config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  
  post "users", to: "users#create"

  devise_for :users

  get "user/show", to: "users#show"

  resources :events
  
  post "attended_event/:id", to: "attended_events#create", as: "attended_event"
  delete "attended_event/:id", to: "attended_events#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attended_events
  has_many :attendees, through: :attended_events, source: :user, dependent: :destroy

  belongs_to :creator, class_name: "User"

  validates :name, presence: true
  validates :info, presence: true
  validates :date, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :attended_events
  has_many :events, through: :attended_events, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/attended_events_controller.rb
class AttendedEventsController < ApplicationController
  def create 
    @event = Event.find(params[:id])
  
    if @event.attendees.exists?(id: current_user.id)
      redirect_to @event, alert: "Error! You already joined the event!"
    else
      @event.attendees << current_user

      if @event.save
        redirect_to @event, notice: "Register succeed! You now joined the event"
      end
    end
  end

  def destroy 
    @event = Event.find(params[:id])

    unless @event.attendees.exists?(id: current_user.id)
      redirect_to @event, alert: "Error! You still not join or already left the event"
    else
      @event.attendees.delete(current_user)

      if @event.save
        redirect_to @event, notice: "You left the event"
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update]

  def index 
    @past_events = Event.all.where("date <= :now", {now: Time.now})
    @future_events = Event.all.where("date > :now", {now: Time.now})
  end

  def show 
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.build()
  end

  def create 
    @event = current_user.created_events.build(event_params)

    if @event.save 
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
    @event = Event.find(params[:id])
  end
  
  def update 
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to user_show_path, notice: "Event removed successfully", status: 303
  end


  private

  def event_params 
    params.require(:event).permit(:name, :info, :date, :location, :creator_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @past_created_events = current_user.created_events.where("date <= :now", {now: Time.now})
    @future_created_events = current_user.created_events.where("date > :now", {now: Time.now})
    @past_attended_events = current_user.events.where("date <= :now", {now: Time.now})
    @future_attended_events = current_user.events.where("date > :now", {now: Time.now})
  end

  def create 
    @user = User.new(user_params)
    @user.save
    sign_in(@user)  
    flash.notice = "User #{@user.name} successfully created! Thank you for signing up!"
    redirect_to user_show_path
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attended_events_helper.rb
module AttendedEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_display_event.html.erb
<strong><%= event.name %></strong><br/>
<p>Information: <%= event.info %></p>
<p>Time: <%= event.date.strftime('%c') %></p>
<p>Location: <%= event.location %></p>

app/views/events/_form.html.erb
<ul>
  <% event.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>


<%= form_with model: event do |form| %>
  <%= form.label :name, "Name:" %><br/>
  <%= form.text_field :name %><br/>
  <%= form.label :info, "Information:" %><br/>
  <%= form.text_area :info %><br/>
  <%= form.label :date, "Time:" %><br/>
  <%= form.datetime_field :date %><br/>
  <%= form.label :location, "Location:" %><br/>
  <%= form.text_field :location %><br/>
  <%= form.submit submit_text %>
<% end %>

app/views/events/_full_display.html.erb
<strong><%= event.name %></strong><br/>
<p>Information: <%= event.info %></p>
<p>Time: <%= event.date.strftime('%c') %></p>
<p>Location: <%= event.location %></p>
<% unless current_user.name == event.creator.name %>
  <p><i>Created by: <%= event.creator.name %></i></p>
<% end %>

<p>Attendees: </p>
<ul>
  <% event.attendees.each do |attendee| %>
    <li>
      <%= attendee.name %>
    </li>
  <% end %>
</ul>

<% unless event.creator_id == current_user.id %>
  <%= button_to 'Join Event', attended_event_path(event), method: :post %>
  <%= button_to 'Left Event', attended_event_path(event), method: :delete %>
<% end %>

app/views/events/_semi_display.html.erb
<strong><%= event.name %></strong>
<p>Time: <%= event.date.strftime('%c') %> </p>
<p>Location: <%= event.location %></p>
<% if user_signed_in? %>
  <% if current_user.name == event.creator.name%>
    <p><i>Created by you</i></p>
  <% else %>
     <p><i>Created by: <%= event.creator.name %></i></p>
  <% end %>
<% else %>
  <p><i>Created by: <%= event.creator.name %></i></p>
<% end %>

<% unless event.id.nil? %>
  <p><%= link_to "More information about the event...", event %></p>
<% end %>

app/views/events/edit.html.erb
<%= render 'events/form', event: @event, submit_text: "Edit Event" %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>
<ul>
  <% @future_events.each do |event| %>
    <li>
      <%= render 'events/semi_display', event: event %>
    </li>
  <% end %>
</ul>

<h1>Past Events</h1>
<ul>
  <% @past_events.each do |event| %>
    <li>
      <%= render 'events/semi_display', event: event %>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<%= render 'events/form', event: @event, submit_text: "Create Event" %>

app/views/events/show.html.erb
<%= render 'events/full_display', event: @event %>

<% if @event.creator_id == current_user.id %>
  <%= link_to "Edit Event", edit_event_path %>
  <%= link_to "Destroy Event", event_path(@event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <% if user_signed_in? %>
      Hello, <%= current_user.name %>!
    <% end %>

    <%= link_to "Home", root_path %>

    <% if user_signed_in? %>
      <%= link_to "Your Events", user_show_path %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path%>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Created Events</h1>

<h2>Upcoming Events</h2>
<ul>
  <% @future_created_events.each do |event| %>
    <li>
      <%= render 'events/semi_display', event: event %>
    </li>
  <% end %>
</ul>

<h2>Past Events</h2>
<ul>
  <% @past_created_events.each do |event| %>
    <li>
      <%= render 'events/semi_display', event: event %>
    </li>
  <% end %>
</ul>

<%= link_to "Create New Event", new_event_path %>

<h1>Attended Events</h1>

<h2>Upcoming Events</h2>
<ul>
  <% @future_attended_events.each do |event| %>
    <li>
      <%= render 'events/semi_display', event: event %>
    </li>
  <% end %>
</ul>

<h2>Past Events</h2>
<ul>
  <% @past_attended_events.each do |event| %>
    <li>
      <%= render 'events/semi_display', event: event %>
    </li>
  <% end %>
</ul>